name: Deploy SSL certificate to AlibabaCloud WAF
description: Deploy SSL certificate to Aliyun Certificates Service (and use in WAF).
branding:
  icon: lock
  color: green
inputs:
  access-key-id:
    description: The accessKeyId used to authenticate with Aliyun. Please specify `access-key-id` and `access-key-secret` or specify `security-token`.
    default: ''
  access-key-secret:
    description: The accessKeySecret used to authenticate with Aliyun. Please specify `access-key-id` and `access-key-secret` or specify `security-token`.
    default: ''
  security-token:
    description: The securityToken (STS) used to authenticate with Aliyun. Please specify `access-key-id` and `access-key-secret` or specify `security-token`.
    default: ''
  fullchain-file:
    description: The file path of the PEM fullchain certificate.
    required: true
  key-file:
    description: The file path of the PEM private key file.
    required: true
  waf-domains:
    description: Enter a list of WAF domains you want to deploy the certificate to.
    required: true
  waf-instance-id:
    description: InstanceId of AlibabaCloud WAF
    required: true
runs:
  using: node16
  main: bootstrap.js
